Repository KeidsID/dicoding-forum-api, pull requests merged in 2023-06, with the labels that each got.

#1 Initial release (v1.0.0)
  .gitignore
  CHANGELOG.md
  README.md
  config/db/structures.md
  migrations/1627983516963_create-table-users.js
  migrations/1627983555473_create-table-authentications.js
  migrations/1686466827448_create-threads-table.js
  migrations/1686469182305_create-thread-comments-table.js
  package.json
  src/Applications/use_case/AddCommentToThreadUsecase.js
  src/Applications/use_case/AddThreadUseCase.js
  src/Applications/use_case/GetCommentsFromThreadUsecase.js
  src/Applications/use_case/GetThreadByIdUsecase.js
  src/Applications/use_case/SoftDeleteCommentUsecase.js
  src/Applications/use_case/_test/AddCommentToThreadUsecase.test.js
  src/Applications/use_case/_test/AddThreadUseCase.test.js
  src/Applications/use_case/_test/GetCommentsFromThread.test.js
  src/Applications/use_case/_test/GetThreadByIdUsecase.test.js
  src/Applications/use_case/_test/SoftDeleteCommentUsecase.test.js
  src/Common/constants.js
  src/Common/exceptions/DomainErrorTranslator.js
  src/Domains/threads/ThreadCommentsRepository.js
  src/Domains/threads/ThreadsRepository.js
  src/Domains/threads/_test/ThreadComentsRepository.test.js
  src/Domains/threads/_test/ThreadsRepository.test.js
  src/Domains/threads/entities/AddedComment.js
  src/Domains/threads/entities/AddedThread.js
  src/Domains/threads/entities/Comment.js
  src/Domains/threads/entities/NewComment.js
  src/Domains/threads/entities/NewThread.js
  src/Domains/threads/entities/Thread.js
  src/Domains/threads/entities/_test/AddedComment.test.js
  src/Domains/threads/entities/_test/AddedThread.test.js
  src/Domains/threads/entities/_test/Comment.test.js
  src/Domains/threads/entities/_test/NewComment.test.js
  src/Domains/threads/entities/_test/NewThread.test.js
  src/Domains/threads/entities/_test/Thread.test.js
  src/Infrastructures/container.js
  src/Infrastructures/http/_test/threads.test.js
  src/Infrastructures/http/_test/users.test.js
  src/Infrastructures/http/createServer.js
  src/Infrastructures/repository/ThreadCommentsRepositoryPostgres.js
  src/Infrastructures/repository/ThreadsRepositoryPostgres.js
  src/Infrastructures/repository/_test/ThreadCommentsRepositoryPostgres.test.js
  src/Infrastructures/repository/_test/ThreadsRepositoryPostgres.test.js
  src/Interfaces/http/api/threads/handler.js
  src/Interfaces/http/api/threads/index.js
  src/Interfaces/http/api/threads/routes.js
  tests/ServerTestHelper.js
  tests/ThreadCommentsTableTestHelper.js
  tests/ThreadsTableTestHelper.js
Labels: enhancement

#4 fix use_cases tests ambiguous mock method
  src/Applications/use_cases/threads/comments/_test/AddCommentToThreadUsecase.test.js
  src/Applications/use_cases/threads/comments/_test/SoftDeleteCommentUsecase.test.js
  src/Applications/use_cases/threads/replies/_test/AddReplyToCommentUsecase.test.js
  src/Applications/use_cases/threads/replies/_test/SoftDeleteReplyUsecase.test.js
Labels: help wanted

#5 Revert "fix use_cases tests ambiguous mock method"
  CHANGELOG.md
  package.json
  src/Applications/use_cases/threads/comments/AddCommentToThreadUsecase.js
  src/Applications/use_cases/threads/comments/SoftDeleteCommentUsecase.js
  src/Applications/use_cases/threads/comments/_test/AddCommentToThreadUsecase.test.js
  src/Applications/use_cases/threads/comments/_test/SoftDeleteCommentUsecase.test.js
  src/Applications/use_cases/threads/replies/AddReplyToCommentUsecase.js
  src/Applications/use_cases/threads/replies/SoftDeleteReplyUsecase.js
  src/Applications/use_cases/threads/replies/_test/AddReplyToCommentUsecase.test.js
  src/Applications/use_cases/threads/replies/_test/SoftDeleteReplyUsecase.test.js
  src/Domains/threads/ThreadsRepository.js
  src/Domains/threads/_test/ThreadsRepository.test.js
  src/Infrastructures/http/_test/threads.test.js
  src/Infrastructures/repository/threads/ThreadsRepositoryPostgres.js
  src/Infrastructures/repository/threads/_test/ThreadsRepositoryPostgres.test.js
Labels: enhancement, help wanted

#6 Fix wrong logic placement
  src/Applications/use_cases/threads/GetThreadByIdUsecase.js
  src/Applications/use_cases/threads/GetThreadDetailsUsecase.js
  src/Applications/use_cases/threads/_test/GetThreadByIdUsecase.test.js
  src/Applications/use_cases/threads/_test/GetThreadDetailsUsecase.test.js
  src/Applications/use_cases/threads/comments/GetCommentsFromThreadUsecase.js
  src/Applications/use_cases/threads/comments/_test/GetCommentsFromThread.test.js
  src/Applications/use_cases/threads/replies/GetRepliesFromCommentUsecase.js
  src/Applications/use_cases/threads/replies/_test/GetRepliesFromCommentUsecase.test.js
  src/Infrastructures/container.js
  src/Interfaces/http/api/threads/handler.js
  src/Interfaces/http/api/threads/routes.js
Labels: help wanted

#7 update missing test
  src/Applications/use_cases/threads/_test/GetThreadDetailsUsecase.test.js
  src/Infrastructures/http/_test/threads.test.js
  src/Infrastructures/repository/threads/_test/ThreadCommentRepliesRepositoryPostgres.test.js
  src/Infrastructures/repository/threads/_test/ThreadCommentsRepositoryPostgres.test.js
  src/Infrastructures/repository/threads/_test/ThreadsRepositoryPostgres.test.js
Labels: help wanted

#8 Replies patch
  README.md
  src/Applications/use_cases/threads/GetThreadDetailsUsecase.js
  src/Applications/use_cases/threads/_test/GetThreadDetailsUsecase.test.js
  src/Domains/threads/replies/ThreadCommentRepliesRepository.js
  src/Domains/threads/replies/_test/ThreadCommentRepliesRepository.test.js
  src/Infrastructures/repository/threads/ThreadCommentRepliesRepositoryPostgres.js
  src/Infrastructures/repository/threads/ThreadCommentsRepositoryPostgres.js
  src/Infrastructures/repository/threads/_test/ThreadCommentRepliesRepositoryPostgres.test.js
  src/Infrastructures/repository/threads/_test/ThreadCommentsRepositoryPostgres.test.js
  src/main.js
Labels: enhancement, help wanted
